#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_learning_kb.py — 生成 web/data/learning.json（学习路线 / 论文 / 仓库 / 课程 / 里程碑）

为什么由脚本生成而不是手写 JSON：
  1. 6 个月的路线是多条 track 的笛卡尔组合，脚本化才能保证 week 编号、任务 id、
     里程碑引用一致（不会出现 W4 的模块引用 W9 的里程碑）。
  2. 每次调用 `collect.py` 或 `daily-agent.md` 增补内容时，脚本可增量合并，
     不会覆盖已有的用户进度（进度存在浏览器 localStorage，与此无关）。
  3. 所有 URL 都是可核查的真实资源；脚本里集中登记便于批量校验。

数据契约见 docs/信息架构与数据契约.md 与 web/assets/js/core.part.js 的
normalizeTrack / normalizeRepo / normalizeCourse / normalizePaper。

用法: python scripts/build_learning_kb.py [--out web/data/learning.json]
"""
from __future__ import annotations

import argparse
import io
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CST = timezone(timedelta(hours=8))


def now() -> str:
    return datetime.now(CST).isoformat(timespec="seconds")


# ---------------------------------------------------------------------------
# 论文：id / 标题 / 年 / 会议 / CCF / 方向 / 真实链接 / 为什么读 / 阅读顺序
# ---------------------------------------------------------------------------
PAPERS = [
    # --- 奠基：必须按顺序吃透 -------------------------------------------------
    dict(id="attention", title="Attention Is All You Need", year=2017, venue="NeurIPS", ccf="A",
         area="foundation", url="https://arxiv.org/abs/1706.03762", readingOrder=1,
         difficulty="easy", mustRead=True, readTime="2h",
         why="一切现代架构的起点。手推一遍 scaled dot-product 与多头拆分，面试必问。",
         keyIdeas=["自注意力替代循环结构，序列内任意位置 O(1) 路径长度",
                   "缩放因子 1/√d_k 抑制点积方差随维度增长", "位置编码用正弦函数注入顺序信息"],
         followUps=["The Annotated Transformer（逐行实现）", "RoPE / ALiBi 等位置编码改进"]),
    dict(id="resnet", title="Deep Residual Learning for Image Recognition", year=2016, venue="CVPR", ccf="A",
         area="foundation", url="https://arxiv.org/abs/1512.03385", readingOrder=2,
         difficulty="easy", mustRead=True, readTime="1h",
         why="残差连接是所有深层网络和 Transformer 子层的基础，理解「恒等映射更容易学」。",
         keyIdeas=["恒等捷径让梯度直达浅层", "退化问题不是过拟合而是优化困难"], followUps=[]),
    dict(id="vit", title="An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
         year=2021, venue="ICLR", ccf="A", area="multimodal",
         url="https://arxiv.org/abs/2010.11929", readingOrder=3, difficulty="medium", mustRead=True,
         readTime="1.5h", why="视觉侧的 Transformer 化，多模态编码器的默认骨架；要能讲清 patch embedding 与归纳偏置的取舍。",
         keyIdeas=["图像切 patch 当 token", "大数据预训练才能弥补缺少局部性先验"], followUps=["Swin Transformer", "DINOv2"]),
    dict(id="clip", title="Learning Transferable Visual Models From Natural Language Supervision",
         year=2021, venue="ICML", ccf="A", area="multimodal",
         url="https://arxiv.org/abs/2103.00020", readingOrder=4, difficulty="medium", mustRead=True,
         readTime="2h", why="图文对齐的奠基工作，对比损失、zero-shot 迁移、prompt engineering 的源头。",
         keyIdeas=["对称 InfoNCE：batch 内其余样本即负样本", "可学习温度控制分布锐度",
                   "batch 越大负样本越多，表示越细"], followUps=["SigLIP（sigmoid 替代 softmax）", "BLIP-2", "LLaVA"]),
    dict(id="ddpm", title="Denoising Diffusion Probabilistic Models", year=2020, venue="NeurIPS", ccf="A",
         area="generative", url="https://arxiv.org/abs/2006.11239", readingOrder=5, difficulty="hard",
         mustRead=True, readTime="3h",
         why="生成建模三大范式之一的开山作。要能从变分下界推到 L_simple，并解释为什么可以丢掉时间权重。",
         keyIdeas=["前向闭式加噪 x_t = √ᾱ_t x_0 + √(1−ᾱ_t) ε",
                   "反向过程等价于预测噪声的 MSE", "与 score matching 的等价关系"], followUps=["DDIM", "Latent Diffusion", "Flow Matching"]),
    dict(id="instructgpt", title="Training language models to follow instructions with human feedback",
         year=2022, venue="NeurIPS", ccf="A", area="posttraining",
         url="https://arxiv.org/abs/2203.02155", readingOrder=6, difficulty="medium", mustRead=True,
         readTime="2h", why="RLHF 三阶段（SFT→RM→PPO）的标准叙事，后训练面试的开场题。",
         keyIdeas=["人类偏好数据训练奖励模型", "PPO + KL 惩罚防止偏离 SFT 太远", "标注一致率是效果上限"],
         followUps=["DPO（去掉奖励模型）", "Constitutional AI"]),
    dict(id="dpo", title="Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
         year=2023, venue="NeurIPS", ccf="A", area="posttraining",
         url="https://arxiv.org/abs/2305.18290", readingOrder=7, difficulty="medium", mustRead=True,
         readTime="2h", why="必考。要能现场推导「隐式奖励」为何与配分项无关，并说清 β 的作用。",
         keyIdeas=["KL 约束下最优策略有闭式解", "隐式奖励 r = β log(π/π_ref)，Z(x) 在成对比较中抵消",
                   "只用偏好对即可训练，无需在线采样"], followUps=["IPO / KTO / ORPO", "SimPO"]),
    dict(id="lora", title="LoRA: Low-Rank Adaptation of Large Language Models", year=2022, venue="ICLR", ccf="A",
         area="engineering", url="https://arxiv.org/abs/2106.09685", readingOrder=8, difficulty="easy",
         mustRead=True, readTime="1.5h", why="实习中最常用的微调手段。A/B 初始化、rank 与 alpha 的关系是高频追问点。",
         keyIdeas=["冻结原权重，只学低秩增量 ΔW = BA", "A 高斯初始化、B 零初始化保证训练起点无扰动",
                   "推理时可合并回原权重，无额外延迟"], followUps=["QLoRA（4bit + 分页优化器）", "DoRA"]),
    dict(id="rope", title="RoFormer: Enhanced Transformer with Rotary Position Embedding",
         year=2021, venue="Neurocomputing", ccf=None, area="foundation",
         url="https://arxiv.org/abs/2104.09864", readingOrder=9, difficulty="medium", mustRead=True,
         readTime="1.5h", why="LLaMA 系全部使用 RoPE。要能解释「旋转后内积只依赖相对距离」，以及外推方案为何要改基频。",
         keyIdeas=["把 d 维两两分组当复数，按位置 m 旋转", "内积只依赖 m−n",
                   "NTK-aware / YaRN 通过缩放 θ 实现长度外推"], followUps=["ALiBi", "YaRN"]),
    dict(id="grpo", title="DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models",
         year=2024, venue="arXiv", ccf=None, area="rl", url="https://arxiv.org/abs/2402.03300",
         readingOrder=10, difficulty="medium", mustRead=True, readTime="2h",
         why="GRPO 的出处，也是「规则奖励 + 组内归一化」能替代 critic 的实践证据。",
         keyIdeas=["组内均值作 baseline，省掉 value network", "用规则校验（答案正确性）做奖励信号",
                   "重要性比 + clip 支持同批数据多次更新"], followUps=["DeepSeek-R1", "DAPO", "RLVR 相关工作"]),
    dict(id="llava", title="Visual Instruction Tuning", year=2023, venue="NeurIPS", ccf="A",
         area="multimodal", url="https://arxiv.org/abs/2304.08485", readingOrder=11,
         difficulty="medium", mustRead=True, readTime="1.5h",
         why="多模态指令微调的标准范式：视觉编码器 + 投影层 + LLM，两条训练阶段。面试常让你对比 BLIP-2 的 Q-Former。",
         keyIdeas=["用 GPT-4 生成图文指令数据", "两阶段：先对齐投影层，再联合指令微调",
                   "极简架构（MLP 投影）也能很强"], followUps=["LLaVA-1.5 / NeXT", "Qwen-VL", "InternVL"]),
    # --- 进阶：按方向选读 -----------------------------------------------------
    dict(id="dit", title="Scalable Diffusion Models with Transformers", year=2023, venue="ICCV", ccf="A",
         area="generative", url="https://arxiv.org/abs/2212.09748", readingOrder=12,
         difficulty="medium", mustRead=False, readTime="1.5h",
         why="DiT 是 Sora 类视频生成模型的骨架；AdaLN 时间步注入是高频考点。",
         keyIdeas=["用 Transformer 替换 U-Net", "adaLN-Zero 把时间步条件注入每个 block",
                   "Gflops 与生成质量强相关"], followUps=["Sora 技术报告", "Latte", "Open-Sora"]),
    dict(id="ldm", title="High-Resolution Image Synthesis with Latent Diffusion Models", year=2022,
         venue="CVPR", ccf="A", area="generative", url="https://arxiv.org/abs/2112.10752",
         readingOrder=13, difficulty="medium", mustRead=False, readTime="2h",
         why="Stable Diffusion 的原型。要能说清 VAE 压缩到潜空间带来多少算力节省。",
         keyIdeas=["在 VAE 潜空间做扩散，降维 4–8 倍", "交叉注意力注入文本条件",
                   "感知压缩与生成学习两阶段解耦"], followUps=["SDXL", "ControlNet"]),
    dict(id="flowmatching", title="Flow Matching for Generative Modeling", year=2023, venue="ICLR", ccf="A",
         area="generative", url="https://arxiv.org/abs/2210.02747", readingOrder=14,
         difficulty="hard", mustRead=False, readTime="2.5h",
         why="新一代生成模型（含部分视频/3D 模型）转向流匹配；面试常问它与扩散的区别。",
         keyIdeas=["直接回归条件向量场，训练目标更简单", "直线路径可少步采样",
                   "与扩散在连续时间极限下统一"], followUps=["Rectified Flow", "Stable Diffusion 3"]),
    dict(id="dreamerv3", title="Mastering Diverse Domains through World Models", year=2023, venue="arXiv",
         ccf=None, area="worldmodel", url="https://arxiv.org/abs/2301.04104", readingOrder=15,
         difficulty="hard", mustRead=False, readTime="3h",
         why="DreamerV3 是世界模型的代表作：在潜空间想象中训练策略，跨域一套超参。",
         keyIdeas=["学习潜动态模型，在想象 rollout 中训练 actor-critic",
                   "symlog 变换处理跨域奖励尺度", "鲁棒性来自模型而非调参"], followUps=["Genie", "TD-MPC2"]),
    dict(id="genie", title="Genie: Generative Interactive Environments", year=2024, venue="ICML", ccf="A",
         area="worldmodel", url="https://arxiv.org/abs/2402.15391", readingOrder=16,
         difficulty="hard", mustRead=False, readTime="2h",
         why="从无标注视频学可交互世界模型；世界模型与生成式模型的交汇点，面试加分项。",
         keyIdeas=["潜动作模型自动发现可控动作", "自回归潜帧预测 + 解码",
                   "单张图即可生成可玩环境"], followUps=["Genie 2/3", "GameNGen"]),
    dict(id="openvla", title="OpenVLA: An Open-Source Vision-Language-Action Model", year=2024,
         venue="CoRL", ccf=None, area="worldmodel", url="https://arxiv.org/abs/2406.09246",
         readingOrder=17, difficulty="medium", mustRead=False, readTime="1.5h",
         why="具身智能方向的入门论文：VLA 如何把动作离散化成 token 并复用 VLM 预训练。",
         keyIdeas=["动作离散化为 token 复用 LLM 词表", "视觉编码器融合 DINOv2 + SigLIP",
                   "LoRA 微调即可超越更大的专用模型"], followUps=["π0", "RT-2", "GR00T"]),
    dict(id="react", title="ReAct: Synergizing Reasoning and Acting in Language Models", year=2023,
         venue="ICLR", ccf="A", area="agent", url="https://arxiv.org/abs/2210.03629", readingOrder=18,
         difficulty="easy", mustRead=False, readTime="1h",
         why="Agent 的最小可行范式：思考-行动-观察循环。面试问 Agent 架构必答。",
         keyIdeas=["把 reasoning trace 与 tool call 交错", "观察结果回灌修正推理",
                   "显著降低幻觉并提升可解释性"], followUps=["Reflexion", "Toolformer", "MCP"]),
    dict(id="flash", title="FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
         year=2022, venue="NeurIPS", ccf="A", area="engineering", url="https://arxiv.org/abs/2205.14135",
         readingOrder=19, difficulty="hard", mustRead=False, readTime="2h",
         why="工程岗高频。核心是 IO 感知的分块与在线 softmax，而不是近似。",
         keyIdeas=["避免把 N×N 注意力矩阵写回 HBM", "tiling + 在线 softmax 重算",
                   "精确注意力但更快更省显存"], followUps=["FlashAttention-2/3", "PagedAttention（vLLM）"]),
    dict(id="scaling", title="Scaling Laws for Neural Language Models", year=2020, venue="arXiv", ccf=None,
         area="foundation", url="https://arxiv.org/abs/2001.08361", readingOrder=20,
         difficulty="medium", mustRead=False, readTime="1.5h",
         why="理解「为什么大家这么在意数据与算力配比」，也是讨论模型规模时的共同语言。",
         keyIdeas=["损失随参数量/数据量/算力幂律下降", "模型形状的影响远小于规模",
                   "存在算力最优的参数量-数据量配比"], followUps=["Chinchilla", "数据质量相关工作"]),
]

# ---------------------------------------------------------------------------
# 仓库：真实、活跃、与方向强相关；含学习计划与检查点
# ---------------------------------------------------------------------------
REPOS = [
    dict(id="minGPT", owner="karpathy", name="minGPT", url="https://github.com/karpathy/minGPT",
         language="Python", area="foundation", difficulty="easy", stars=21000, status="active",
         why="300 行讲清 GPT 训练与推理；第一次手写 Transformer 的最佳起点。",
         studyPlan=["通读 model.py 并画出计算图", "在字符级数据集上训练一个迷你 GPT",
                    "把 attention 换成 FlashAttention 版本对比速度"],
         checkpoints=["能默写 MultiHeadAttention", "能解释 causal mask 的实现位置"]),
    dict(id="nanoGPT", owner="karpathy", name="nanoGPT", url="https://github.com/karpathy/nanoGPT",
         language="Python", area="engineering", difficulty="medium", stars=40000, status="active",
         why="可复现的训练脚本，包含 DDP、混合精度、梯度累积等真实工程细节。",
         studyPlan=["跑通 shakespeare_char 快速实验", "读 train.py 的 DDP 部分",
                    "改一处超参并记录 loss 曲线差异"],
         checkpoints=["能说清 DDP 与 DataParallel 的区别", "能解释梯度累积如何等效大 batch"]),
    dict(id="transformers", owner="huggingface", name="transformers", url="https://github.com/huggingface/transformers",
         language="Python", area="engineering", difficulty="medium", stars=130000, status="active",
         why="模型实现的事实标准；面试问「某某模型的实现细节」时这里是一手答案。",
         studyPlan=["读 modeling_llama.py 的 attention 与 RoPE 实现",
                    "用 Trainer 跑一次 LoRA 微调", "对比不同模型的 generate 策略实现"],
         checkpoints=["能在不查文档的情况下接入一个自定义模型", "能解释 KV cache 的复用方式"]),
    dict(id="peft", owner="huggingface", name="peft", url="https://github.com/huggingface/peft",
         language="Python", area="engineering", difficulty="easy", stars=17000, status="active",
         why="LoRA/QLoRA/P-Tuning 等参数高效微调的统一实现，实习任务最常用的库。",
         studyPlan=["用 LoraConfig 微调一个小模型", "读 LoRA 层的 merge/unmerge 实现",
                    "对比不同 target_modules 的效果"],
         checkpoints=["能说明 rank 与 alpha 对更新的影响", "能解释为什么 B 初始化为零"]),
    dict(id="trl", owner="huggingface", name="trl", url="https://github.com/huggingface/trl",
         language="Python", area="posttraining", difficulty="medium", stars=13000, status="active",
         why="SFT / DPO / GRPO / PPO 的官方实现集合，后训练方向必读源码。",
         studyPlan=["读 DPOTrainer 的 loss 实现并与论文公式对照",
                    "跑通一个小规模 DPO 实验", "读 GRPO 的 advantage 计算"],
         checkpoints=["能指出 DPO 实现里 logp 的掩码位置", "能解释参考模型如何冻结"]),
    dict(id="deepspeed", owner="deepspeedai", name="DeepSpeed", url="https://github.com/deepspeedai/DeepSpeed",
         language="Python", area="engineering", difficulty="hard", stars=37000, status="active",
         why="ZeRO 三阶段的参考实现，分布式训练面试的核心考点。",
         studyPlan=["读 ZeRO 论文并对照代码", "跑通 ZeRO-2 与 ZeRO-3 的显存对比",
                    "分析通信量与显存的分段权衡"],
         checkpoints=["能画出 ZeRO-1/2/3 的切分对象", "能说清 offload 的代价"]),
    dict(id="vllm", owner="vllm-project", name="vllm", url="https://github.com/vllm-project/vllm",
         language="Python", area="engineering", difficulty="hard", stars=48000, status="active",
         why="PagedAttention 与连续批处理的生产级实现，推理加速方向必读。",
         studyPlan=["读 PagedAttention 论文与 block_manager 实现",
                    "压测不同并发下的吞吐/延迟", "对比 prefix caching 开关的效果"],
         checkpoints=["能解释 KV cache 分页如何消除显存碎片", "能说清 continuous batching 的收益来源"]),
    dict(id="open_clip", owner="mlfoundations", name="open_clip", url="https://github.com/mlfoundations/open_clip",
         language="Python", area="multimodal", difficulty="medium", stars=12000, status="active",
         why="CLIP 的可复现训练与评测实现，多模态对齐的第一份可跑代码。",
         studyPlan=["跑 zero-shot 评测", "读对比损失的实现与分布式负样本收集",
                    "用小数据集跑一次完整训练"],
         checkpoints=["能解释 all_gather 对负样本的意义", "能说清 logit_scale 的约束"]),
    dict(id="llava", owner="haotian-liu", name="LLaVA", url="https://github.com/haotian-liu/LLaVA",
         language="Python", area="multimodal", difficulty="medium", stars=23000, status="active",
         why="视觉指令微调的标准实现，两阶段训练流程完整可复现。",
         studyPlan=["读投影层与数据构造脚本", "跑一次小规模两阶段训练",
                    "对比不同视觉编码器的影响"],
         checkpoints=["能画出 MLLM 的数据流", "能解释为什么需要先冻 LLM 只训投影层"]),
    dict(id="diffusers", owner="huggingface", name="diffusers", url="https://github.com/huggingface/diffusers",
         language="Python", area="generative", difficulty="medium", stars=28000, status="active",
         why="扩散与流匹配模型的统一实现，采样器与调度器的最佳参考。",
         studyPlan=["读 DDPM/DDIM/Euler 调度器的数学实现", "跑文生图并对比不同采样步数",
                    "实现一个自定义 scheduler"],
         checkpoints=["能解释训练步数与采样步数为何可以不同", "能说清 guidance scale 的作用"]),
    dict(id="diffusion_policy", owner="real-stanford", name="diffusion_policy", url="https://github.com/real-stanford/diffusion_policy",
         language="Python", area="worldmodel", difficulty="hard", stars=3600, status="active",
         why="把扩散用于机器人动作生成的代表作，具身方向常被引用。",
         studyPlan=["读动作去噪的表示方式", "在仿真环境跑一个任务",
                    "对比扩散策略与行为克隆基线"],
         checkpoints=["能解释为什么动作也要当成生成问题", "能说清 receding horizon 的控制含义"]),
    dict(id="gymnasium", owner="Farama-Foundation", name="Gymnasium", url="https://github.com/Farama-Foundation/Gymnasium",
         language="Python", area="rl", difficulty="easy", stars=8000, status="active",
         why="RL 环境接口标准；配合 PPO 实现理解 advantage 与 GAE。",
         studyPlan=["跑通 CartPole 的 PPO", "手写 GAE 并与库实现对比",
                    "记录不同 λ 下的方差/偏差"],
         checkpoints=["能推导 GAE 的递推式", "能解释 clip 如何限制策略更新"]),
    dict(id="cleanrl", owner="vwxyzjn", name="cleanrl", url="https://github.com/vwxyzjn/cleanrl",
         language="Python", area="rl", difficulty="medium", stars=8000, status="active",
         why="单文件 RL 算法实现，PPO 那一份是面试前复习 advantage 的最好材料。",
         studyPlan=["逐行读 ppo.py", "改 reward shaping 观察行为变化",
                    "把 PPO 与 GRPO 的 advantage 处理并排对比"],
         checkpoints=["能说清 PPO 与 GRPO 的 baseline 来源差异", "能解释价值网络的损失构成"]),
    dict(id="leetcodepatterns", owner="donnemartin", name="system-design-primer",
         url="https://github.com/donnemartin/system-design-primer", language="Markdown",
         area="engineering", difficulty="easy", stars=290000, status="active",
         why="系统设计题的通用词汇表；算法实习的笔试/面试常考工程权衡题。",
         studyPlan=["读缓存与一致性章节", "用自己的项目复述一次权衡",
                    "准备 3 个可讲的工程决策故事"],
         checkpoints=["能在 5 分钟内讲清一次容量估算", "能说出至少 4 组经典权衡"]),
    dict(id="the_algorithms", owner="TheAlgorithms", name="Python",
         url="https://github.com/TheAlgorithms/Python", language="Python", area="foundation",
         difficulty="easy", stars=200000, status="active",
         why="手撕题的标准写法参考；二分、DP、并查集、单调栈都能找到干净实现。",
         studyPlan=["每天手写 2 道高频题并对照实现", "整理易错边界到一个笔记文件",
                    "用 30 天覆盖所有高频主题"],
         checkpoints=["能在 15 分钟内无提示写出并查集", "能一次写对二分的边界"]),
    dict(id="awesome_llm", owner="Hannibal046", name="Awesome-LLM",
         url="https://github.com/Hannibal046/Awesome-LLM", language="Markdown", area="trend",
         difficulty="easy", stars=25000, status="active",
         why="大模型方向的持续追踪清单，用来保证「不遗漏重要工作」。",
         studyPlan=["订阅仓库更新", "每周挑 1 篇新论文做笔记",
                    "把与自己方向相关的工作加进本工作台"],
         checkpoints=["能说出近半年你方向上的 3 个主线变化"]),
]

# ---------------------------------------------------------------------------
# 课程
# ---------------------------------------------------------------------------
COURSES = [
    dict(id="cs231n", title="CS231n: Deep Learning for Computer Vision", provider="Stanford", year=2025,
         url="https://cs231n.stanford.edu/", language="en", hours=60, level="intermediate",
         area="vision", hasAssignments=True, status="active",
         why="视觉方向最扎实的基础课，作业质量极高（手写反向传播、CNN、注意力）。",
         modules=["反向传播手推", "CNN 与批归一化", "注意力与 Transformer", "生成模型导论"]),
    dict(id="cs224n", title="CS224n: Natural Language Processing with Deep Learning", provider="Stanford",
         year=2025, url="https://web.stanford.edu/class/cs224n/", language="en", hours=55,
         level="intermediate", area="nlp", hasAssignments=True, status="active",
         why="从词向量到 LLM 后训练的完整链路，作业含手写注意力与提示工程。",
         modules=["词表示", "注意力与 Transformer", "预训练", "后训练与对齐"]),
    dict(id="d2l", title="动手学深度学习 (D2L)", provider="李沐 / 开源社区", year=2025,
         url="https://zh.d2l.ai/", language="zh", hours=80, level="beginner", area="foundation",
         hasAssignments=True, status="active",
         why="中文最佳入门教材，代码与数学并重，适合快速补齐工程直觉。",
         modules=["线性回归与 Softmax", "多层感知机", "卷积网络", "注意力机制", "优化算法"]),
    dict(id="hungyi", title="李宏毅机器学习 / 生成式 AI 导论", provider="NTU 李宏毅", year=2025,
         url="https://speech.ee.ntu.edu.tw/~hylee/ml/2025-spring.php", language="zh", hours=50,
         level="beginner", area="generative", hasAssignments=True, status="active",
         why="中文讲解生成式模型与 RLHF 最清晰的课程之一，适合建立整体图景。",
         modules=["Transformer", "自监督预训练", "RLHF 与 DPO", "扩散模型"]),
    dict(id="spinningup", title="Spinning Up in Deep RL", provider="OpenAI", year=2018,
         url="https://spinningup.openai.com/", language="en", hours=25, level="intermediate",
         area="rl", hasAssignments=False, status="active",
         why="RL 从零到 PPO 的最短路径，术语与实现对齐。",
         modules=["RL 核心概念", "策略梯度", "TRPO/PPO", "探索与离线 RL"]),
    dict(id="hf_course", title="Hugging Face LLM Course", provider="Hugging Face", year=2025,
         url="https://huggingface.co/learn/llm-course", language="en", hours=30, level="intermediate",
         area="engineering", hasAssignments=True, status="active",
         why="贴近工程实践：训练、微调、量化、部署一条线走通。",
         modules=["Transformer 生态", "微调与 PEFT", "数据集与评测", "部署与推理优化"]),
    dict(id="mit6s191", title="MIT 6.S191: Introduction to Deep Learning", provider="MIT", year=2025,
         url="http://introtodeeplearning.com/", language="en", hours=20, level="beginner",
         area="foundation", hasAssignments=True, status="active",
         why="节奏快的综述课，适合在面试前用 2 周快速回扫全局。",
         modules=["深度学习基础", "CNN/RNN", "生成模型", "强化学习入门"]),
    dict(id="fastai", title="Practical Deep Learning for Coders", provider="fast.ai", year=2025,
         url="https://course.fast.ai/", language="en", hours=45, level="beginner", area="engineering",
         hasAssignments=True, status="active",
         why="自上而下的教学法，适合快速获得「能跑出结果」的信心。",
         modules=["训练第一模型", "生产部署", "从零实现", "调参与泛化"]),
]

# ---------------------------------------------------------------------------
# 路线：模块化的周计划，任务带验收标准
# ---------------------------------------------------------------------------
TRACKS = [
    dict(
        id="mllm", name="多模态大模型 (MLLM)", level="core", durationWeeks=8,
        goal="能独立复现并改进一个 VLM 的视觉-语言对齐训练，并能讲清 LLaVA / BLIP-2 / Qwen-VL 的架构差异。",
        prerequisites=["PyTorch 熟练", "Transformer 原理", "线性代数与概率基础"],
        modules=[
            dict(title="视觉编码器与对齐基础", week=1, hours=14,
                 objectives=["理解 ViT 的 patch 化与归纳偏置取舍", "掌握对比学习的 InfoNCE 与温度"],
                 concepts=["ViT", "patch embedding", "对比学习", "InfoNCE"],
                 tasks=[
                     dict(title="精读 CLIP 并手推 InfoNCE 双向损失", type="paper", estimateHours=3,
                          deliverable="一页笔记 + 手写公式照片", done="能不看资料写出双向交叉熵并解释温度作用"),
                     dict(title="跑通 open_clip 的 zero-shot 评测", type="code", estimateHours=2,
                          deliverable="评测脚本与结果表", done="能说明 prompt engineering 对结果的影响幅度"),
                     dict(title="精读 ViT，写清 patch 化带来的取舍", type="paper", estimateHours=2,
                          deliverable="笔记", done="能回答「小数据集上 ViT 为什么不如 CNN」"),
                 ],
                 paperIds=["vit", "clip"], repoIds=["open_clip"], courseIds=["cs231n"]),
            dict(title="MLLM 架构与两阶段训练", week=2, hours=16,
                 objectives=["掌握投影层对齐 + 指令微调的两阶段范式", "能对比 Q-Former 与 MLP 投影"],
                 concepts=["视觉-语言投影", "Q-Former", "两阶段训练", "模态对齐"],
                 tasks=[
                     dict(title="精读 LLaVA 与 BLIP-2，画架构对比图", type="paper", estimateHours=3,
                          deliverable="对比表格", done="能说清两者在 token 数量与训练成本上的差异"),
                     dict(title="手写一个最小 VLM（ViT + MLP + 小 LLM）", type="project", estimateHours=6,
                          deliverable="可运行代码", done="能在玩具数据上过拟合一个 batch"),
                     dict(title="读 LLaVA 数据构造脚本", type="code", estimateHours=2,
                          deliverable="数据格式说明", done="能自己造 100 条图文指令数据"),
                 ],
                 paperIds=["llava"], repoIds=["llava", "transformers"], courseIds=["cs224n"]),
            dict(title="多模态后训练与评测", week=3, hours=14,
                 objectives=["理解多模态 SFT 与偏好优化的差异", "掌握主流多模态评测基准"],
                 concepts=["多模态 SFT", "多模态偏好优化", "幻觉评测", "MMBench"],
                 tasks=[
                     dict(title="在小型 VLM 上做一次 LoRA SFT", type="project", estimateHours=5,
                          deliverable="训练日志与 loss 曲线", done="能解释过拟合出现的步数与应对手段"),
                     dict(title="整理 5 个多模态评测基准的考察点", type="study", estimateHours=3,
                          deliverable="评测对照表", done="能说出每个基准最容易刷分的偏差来源"),
                 ],
                 paperIds=["clip", "llava"], repoIds=["peft", "llava"], courseIds=["hf_course"]),
            dict(title="项目：复现 + 一处改进", week=4, hours=20,
                 objectives=["把一个想法落到可度量的改进上"],
                 concepts=["消融实验", "复现纪律"],
                 tasks=[
                     dict(title="选定一个 VLM 做复现，记录基线指标", type="project", estimateHours=8,
                          deliverable="复现报告", done="指标与论文差距在可解释范围内"),
                     dict(title="提出并验证一处改进（数据/结构/训练策略）", type="project", estimateHours=8,
                          deliverable="消融实验表", done="改进有统计意义且能解释原因"),
                 ],
                 paperIds=[], repoIds=["llava"], courseIds=[]),
        ]),
    dict(
        id="posttrain", name="后训练 (Post-training)", level="core", durationWeeks=8,
        goal="能完整讲清 SFT → 奖励建模 → 在线/离线偏好优化的取舍，并能手写 DPO / GRPO 损失与其工程细节。",
        prerequisites=["Transformer 与语言模型基础", "PyTorch 训练脚本经验", "概率与优化基础"],
        modules=[
            dict(title="SFT 与指令微调", week=1, hours=12,
                 objectives=["掌握数据配比与 loss 掩码", "理解灾难性遗忘与缓解手段"],
                 concepts=["指令数据构造", "loss masking", "数据配比", "灾难性遗忘"],
                 tasks=[
                     dict(title="用 LoRA 微调一个小模型并在自建 100 条测试集上评测", type="project",
                          estimateHours=5, deliverable="评测报告", done="能解释评测集设计如何避免泄漏"),
                     dict(title="精读 InstructGPT，画出三阶段流程图", type="paper", estimateHours=3,
                          deliverable="流程图", done="能说明每一阶段的数据来源与目标函数"),
                 ],
                 paperIds=["instructgpt", "lora"], repoIds=["peft", "trl"], courseIds=["hf_course"]),
            dict(title="偏好优化：DPO 家族", week=2, hours=16,
                 objectives=["独立推导 DPO", "分辨 DPO/IPO/KTO/ORPO/SimPO 的动机差异"],
                 concepts=["隐式奖励", "KL 约束", "参考模型", "偏好数据"],
                 tasks=[
                     dict(title="手推 DPO 并从 KL 约束目标出发写清每一步", type="paper", estimateHours=4,
                          deliverable="推导笔记", done="能解释为什么不需要奖励模型"),
                     dict(title="读 trl 的 DPOTrainer 损失实现并逐行对应公式", type="code", estimateHours=3,
                          deliverable="带注释源码", done="能指出 completion mask 的处理位置"),
                     dict(title="跑一次小规模 DPO，观察 β 对输出的影响", type="project", estimateHours=4,
                          deliverable="实验对比", done="能解释 β 过大/过小的症状"),
                     dict(title="对比 4 种偏好优化变体的损失差异", type="paper", estimateHours=4,
                          deliverable="对比表", done="能回答「什么场景该选哪个」"),
                 ],
                 paperIds=["dpo"], repoIds=["trl", "transformers"], courseIds=["hungyi"]),
            dict(title="在线 RL：PPO 与 GRPO", week=3, hours=16,
                 objectives=["掌握 GAE 与优势估计", "理解 GRPO 为何能去掉 critic"],
                 concepts=["GAE", "优势估计", "clip 目标", "组内归一化", "规则奖励"],
                 tasks=[
                     dict(title="手推 GAE 递推式并用 cleanrl 对照验证", type="code", estimateHours=4,
                          deliverable="推导 + 数值验证脚本", done="自己实现的 GAE 与库结果误差 <1e-6"),
                     dict(title="精读 GRPO，写出组内优势公式与退化情况", type="paper", estimateHours=3,
                          deliverable="笔记", done="能说明组内方差为 0 时该怎么处理"),
                     dict(title="对比 PPO 与 GRPO 的显存/样本效率", type="study", estimateHours=3,
                          deliverable="对照表", done="能解释省掉的 value network 值多少显存"),
                 ],
                 paperIds=["grpo"], repoIds=["cleanrl", "gymnasium", "trl"], courseIds=["spinningup"]),
            dict(title="项目：可验证奖励的 RL 微调", week=4, hours=20,
                 objectives=["跑通一条「规则奖励 → RL → 指标提升」的闭环"],
                 concepts=["RLVR", "奖励设计", "评测闭环"],
                 tasks=[
                     dict(title="用一个可自动判分的小任务做 GRPO 训练", type="project", estimateHours=10,
                          deliverable="训练脚本 + 曲线", done="准确率相对 SFT 基线有可重复提升"),
                     dict(title="分析失败样本，写清奖励设计的漏洞", type="study", estimateHours=5,
                          deliverable="失败分析报告", done="能提出至少 2 个奖励改进方案"),
                 ],
                 paperIds=["grpo", "dpo"], repoIds=["trl"], courseIds=[]),
        ]),
    dict(
        id="gen", name="生成式模型 (Diffusion / Flow)", level="core", durationWeeks=7,
        goal="从变分下界推到 Flow Matching，能手写 DDPM 训练循环并解释采样加速的原理与代价。",
        prerequisites=["概率论（高斯、KL、变分推断）", "PyTorch", "CNN/Transformer"],
        modules=[
            dict(title="扩散模型原理", week=1, hours=16,
                 objectives=["从 ELBO 推到 L_simple", "理解与 score matching 的等价性"],
                 concepts=["前向/反向过程", "重参数化", "ELBO", "score matching"],
                 tasks=[
                     dict(title="精读 DDPM 并完整推导 L_simple", type="paper", estimateHours=5,
                          deliverable="推导笔记", done="能解释为什么可以丢掉时间权重"),
                     dict(title="从零实现 2D 玩具数据的扩散模型", type="project", estimateHours=5,
                          deliverable="可视化采样过程", done="能生成合理的双月分布样本"),
                     dict(title="实现并对比 DDPM 与 DDIM 采样", type="code", estimateHours=4,
                          deliverable="速度/质量对比", done="能说明少步采样的质量损失来源"),
                 ],
                 paperIds=["ddpm"], repoIds=["diffusers"], courseIds=["hungyi"]),
            dict(title="潜空间扩散与条件生成", week=2, hours=14,
                 objectives=["掌握 VAE 压缩的收益与代价", "理解交叉注意力文本条件注入"],
                 concepts=["潜空间", "VAE", "交叉注意力", "classifier-free guidance"],
                 tasks=[
                     dict(title="精读 LDM，量化潜空间带来的算力节省", type="paper", estimateHours=3,
                          deliverable="算力估算笔记", done="能算出一个具体分辨率下的 FLOPs 倍数"),
                     dict(title="调整 guidance scale 并记录质量-多样性权衡", type="project", estimateHours=4,
                          deliverable="对比图与结论", done="能解释 guidance 过大导致的问题"),
                 ],
                 paperIds=["ldm"], repoIds=["diffusers"], courseIds=["cs231n"]),
            dict(title="DiT 与视频生成", week=3, hours=14,
                 objectives=["理解 Transformer 化扩散与时间步条件注入", "了解视频生成的核心难点"],
                 concepts=["DiT", "adaLN-Zero", "时空注意力", "长视频一致性"],
                 tasks=[
                     dict(title="精读 DiT，写清 adaLN 的三种变体差异", type="paper", estimateHours=3,
                          deliverable="笔记", done="能解释 adaLN-Zero 为什么训练更稳"),
                     dict(title="阅读一个开源视频生成项目的注意力设计", type="code", estimateHours=5,
                          deliverable="架构笔记", done="能说清时空注意力的显存瓶颈与拆解方案"),
                 ],
                 paperIds=["dit"], repoIds=["diffusers"], courseIds=[]),
            dict(title="项目：条件生成小项目", week=4, hours=18,
                 objectives=["完成一次带条件的生成训练并做消融"],
                 concepts=["条件注入", "评测指标 FID", "消融"],
                 tasks=[
                     dict(title="训练一个类别条件生成模型并计算 FID", type="project", estimateHours=10,
                          deliverable="代码 + 指标", done="FID 相对无条件基线显著下降"),
                     dict(title="对比两种条件注入方式", type="project", estimateHours=6,
                          deliverable="消融表", done="能解释差异的机制而非只报数字"),
                 ],
                 paperIds=["dit", "ldm"], repoIds=["diffusers"], courseIds=[]),
        ]),
    dict(
        id="world", name="世界模型与具身智能", level="advanced", durationWeeks=8,
        goal="理解「学一个可 rollout 的环境模型」这一主线，并能讲清 Dreamer / Genie / VLA 三类工作的差异。",
        prerequisites=["强化学习基础", "生成模型基础", "机器人或控制基础（加分）"],
        modules=[
            dict(title="基于模型的 RL", week=1, hours=14,
                 objectives=["掌握潜动态模型 + 想象 rollout 的训练范式"],
                 concepts=["潜动态", "想象 rollout", "模型误差累积", "MBRL"],
                 tasks=[
                     dict(title="精读 DreamerV3，画出训练循环", type="paper", estimateHours=4,
                          deliverable="流程图", done="能解释 actor-critic 为何在潜空间训练"),
                     dict(title="在 Gymnasium 环境跑通一个 MBRL 基线", type="code", estimateHours=6,
                          deliverable="训练曲线", done="能说出与无模型方法的样本效率差异"),
                 ],
                 paperIds=["dreamerv3"], repoIds=["gymnasium", "cleanrl"], courseIds=["spinningup"]),
            dict(title="生成式世界模型", week=2, hours=14,
                 objectives=["理解从视频学可交互环境的关键设计"],
                 concepts=["潜动作", "自回归视频预测", "可控性"],
                 tasks=[
                     dict(title="精读 Genie，写清潜动作模型的作用", type="paper", estimateHours=4,
                          deliverable="笔记", done="能解释无标注视频如何提供动作监督"),
                     dict(title="对比 Genie 与 Dreamer 的监督信号来源", type="study", estimateHours=3,
                          deliverable="对照表", done="能说清两者对数据的要求差异"),
                 ],
                 paperIds=["genie"], repoIds=[], courseIds=[]),
            dict(title="VLA 与具身策略", week=3, hours=14,
                 objectives=["掌握 VLA 的动作表示与训练方式"],
                 concepts=["动作离散化", "VLA", "模仿学习", "receding horizon"],
                 tasks=[
                     dict(title="精读 OpenVLA，写清动作 token 化细节", type="paper", estimateHours=4,
                          deliverable="笔记", done="能解释为什么复用 LLM 词表能加速收敛"),
                     dict(title="阅读 diffusion policy 的动作表示", type="code", estimateHours=4,
                          deliverable="对比笔记", done="能说清扩散策略与回归策略的取舍"),
                 ],
                 paperIds=["openvla"], repoIds=["diffusion_policy"], courseIds=[]),
            dict(title="项目：世界模型小实验", week=4, hours=18,
                 objectives=["完成一次「学模型 → 规划/控制」的闭环"],
                 concepts=["模型预测控制", "误差累积", "评测"],
                 tasks=[
                     dict(title="在简单环境上实现 model-based 控制", type="project", estimateHours=10,
                          deliverable="代码 + 对比曲线", done="在样本效率上优于随机基线"),
                     dict(title="分析模型误差累积的拐点", type="study", estimateHours=4,
                          deliverable="分析报告", done="能给出 horizon 选择的经验规则"),
                 ],
                 paperIds=["dreamerv3"], repoIds=["gymnasium"], courseIds=[]),
        ]),
    dict(
        id="agent", name="Agent 理论与实践", level="support", durationWeeks=4,
        goal="能用最小实现讲清 Agent 的规划-工具-记忆三件套，并了解评测与安全的基本问题。",
        prerequisites=["LLM 基础", "Python 工程能力"],
        modules=[
            dict(title="Agent 范式", week=1, hours=10,
                 objectives=["掌握 ReAct 循环与工具调用协议"],
                 concepts=["ReAct", "工具调用", "观察回灌", "MCP"],
                 tasks=[
                     dict(title="精读 ReAct 并手写一个最小 Agent", type="project", estimateHours=5,
                          deliverable="可运行代码", done="能完成需要 3 步工具调用的任务"),
                     dict(title="整理主流 Agent 框架的设计差异", type="study", estimateHours=3,
                          deliverable="对比表", done="能说出状态管理与错误恢复的两种策略"),
                 ],
                 paperIds=["react"], repoIds=[], courseIds=[]),
            dict(title="记忆、规划与评测", week=2, hours=10,
                 objectives=["理解长程任务中的记忆与失败恢复", "了解 Agent 评测基准"],
                 concepts=["长期记忆", "任务分解", "Agent 评测", "安全边界"],
                 tasks=[
                     dict(title="实现带记忆的 Agent 并做失败案例分析", type="project", estimateHours=6,
                          deliverable="案例报告", done="能给出至少 3 类失败的根因"),
                 ],
                 paperIds=["react"], repoIds=[], courseIds=[]),
        ]),
    dict(
        id="eng", name="工程与系统（支撑）", level="support", durationWeeks=5,
        goal="能独立跑起一次多卡/显存受限训练与一次高吞吐推理，并解释清楚每个优化点的收益来源。",
        prerequisites=["PyTorch", "Linux 命令行", "基础 CUDA 概念"],
        modules=[
            dict(title="分布式训练", week=1, hours=12,
                 objectives=["分清 DP/DDP/FSDP/ZeRO 的切分对象"],
                 concepts=["DDP", "ZeRO", "FSDP", "混合精度", "梯度累积"],
                 tasks=[
                     dict(title="读 ZeRO 论文并画出三阶段切分", type="paper", estimateHours=4,
                          deliverable="示意图", done="能说出各阶段省的是什么显存"),
                     dict(title="用 DDP 跑一次多卡训练并记录加速比", type="project", estimateHours=5,
                          deliverable="训练日志", done="能解释加速比低于线性的原因"),
                 ],
                 paperIds=[], repoIds=["deepspeed", "nanoGPT"], courseIds=["hf_course"]),
            dict(title="推理加速", week=2, hours=12,
                 objectives=["掌握 KV cache、连续批处理与量化的收益与代价"],
                 concepts=["KV cache", "PagedAttention", "continuous batching", "量化"],
                 tasks=[
                     dict(title="压测 vLLM 的吞吐-延迟曲线", type="project", estimateHours=5,
                          deliverable="压测报告", done="能解释吞吐随并发上升后为何持平"),
                     dict(title="对比 fp16/int8 量化的质量损失", type="project", estimateHours=4,
                          deliverable="对比表", done="能说明量化误差主要来自哪些层"),
                 ],
                 paperIds=["flash"], repoIds=["vllm", "transformers"], courseIds=[]),
        ]),
]

MILESTONES = [
    dict(id="m1", week=2, title="Transformer 从零实现通过自测",
         acceptance=["手写 MHA 与论文逐项对齐", "能默写 causal mask 与缩放位置", "训练 loss 单调下降"],
         evidence="GitHub commit + 单元测试", trackIds=["mllm", "posttrain"]),
    dict(id="m2", week=3, title="CLIP 对比损失可独立推导并复现",
         acceptance=["能写出双向 InfoNCE", "能解释温度与 batch size 的作用", "跑通 zero-shot 评测"],
         evidence="推导笔记 + 评测结果", trackIds=["mllm"]),
    dict(id="m3", week=4, title="完成一次 LoRA 微调并做评测",
         acceptance=["自建测试集无泄漏", "能解释 rank/alpha 影响", "给出前后对比数字"],
         evidence="实验报告", trackIds=["mllm", "posttrain"]),
    dict(id="m4", week=5, title="DPO 损失手写并通过数值对照",
         acceptance=["闭式推导完整", "与 trl 实现误差 <1e-5", "能解释 β 的取舍"],
         evidence="代码 + 推导", trackIds=["posttrain"]),
    dict(id="m5", week=6, title="GRPO 小任务闭环跑通",
         acceptance=["规则奖励可自动判分", "相对 SFT 有可重复提升", "失败样本有归因"],
         evidence="训练曲线 + 失败分析", trackIds=["posttrain"]),
    dict(id="m6", week=6, title="从零实现 2D 扩散模型",
         acceptance=["闭式加噪正确", "能生成合理分布", "DDIM 少步采样可对比"],
         evidence="可视化 + 代码", trackIds=["gen"]),
    dict(id="m7", week=7, title="完成一个带条件的生成项目",
         acceptance=["有 FID 等客观指标", "至少一组消融", "能解释机制"],
         evidence="消融表", trackIds=["gen"]),
    dict(id="m8", week=8, title="世界模型闭环实验",
         acceptance=["实现学模型-控制闭环", "样本效率优于随机基线", "给出 horizon 经验规则"],
         evidence="对比曲线", trackIds=["world"]),
    dict(id="m9", week=5, title="多卡训练与推理压测各完成一次",
         acceptance=["记录加速比并可解释", "吞吐-延迟曲线完整", "能说清瓶颈在哪"],
         evidence="压测报告", trackIds=["eng"]),
    dict(id="m10", week=8, title="手撕题覆盖全部高频主题",
         acceptance=["每主题至少 5 题", "18 分钟内无提示写出 MHA", "整理成易错清单"],
         evidence="题库进度 100%", trackIds=["mllm", "posttrain", "gen", "world"]),
    dict(id="m11", week=9, title="简历项目可 5 分钟讲清",
         acceptance=["问题-方法-结果三段式", "有可量化结果", "能回答三连追问"],
         evidence="模拟面试录像", trackIds=["mllm", "posttrain", "gen", "world"]),
    dict(id="m12", week=10, title="完成 3 次模拟面试并复盘",
         acceptance=["每次记录卡壳点", "第二次不重复同类错误", "形成个人答题框架"],
         evidence="复盘文档", trackIds=["mllm", "posttrain", "gen", "world"]),
]

STUDY_SYSTEM = dict(
    weeklyRhythm=[
        "周一 / 周三：论文精读 2h（先摘要与图表，再推导，最后写 5 行结论）",
        "周二 / 周四：代码复现 3h（改一处、跑一次、记录差异）",
        "周五：整理本周笔记并更新工作台进度",
        "周六：手撕题 2h（限时，写完立即对照参考实现）",
        "周日：周复盘 1h + 下周计划（写进工作台的路线勾选）",
    ],
    spacedRepetition=dict(
        enabled=True, intervals=[1, 3, 7, 16, 35],
        rule="每个知识点在 1/3/7/16/35 天后各复习一次；答不出就回到第 1 天重新计时。复习时只允许看标题自述内容。",
    ),
    noteTemplate=["一句话结论", "它解决什么问题（没有它会怎样）", "方法要点（≤5 条）",
                  "我的疑问（必须写，写不出说明没读透）", "可复用代码片段或公式", "能用在哪个项目里"],
    antiPatterns=["只收藏不阅读", "复现不跑通就换下一个", "不做复盘就开新坑",
                  "把摘要当理解", "面试前一周才开始刷手撕题"],
)


def build() -> dict:
    return dict(
        meta=dict(
            generatedAt=now(),
            source="build_learning_kb.py",
            placeholder=False,
            note="由脚本生成，保证 track/module/task id 与里程碑引用一致；URL 均为真实资源。",
            counts=dict(tracks=len(TRACKS), papers=len(PAPERS), repos=len(REPOS),
                        courses=len(COURSES), milestones=len(MILESTONES)),
        ),
        tracks=TRACKS,
        papers=PAPERS,
        repos=REPOS,
        courses=COURSES,
        milestones=MILESTONES,
        studySystem=STUDY_SYSTEM,
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="build_learning_kb.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(ROOT / "web" / "data" / "learning.json"))
    args = ap.parse_args(argv)

    payload = build()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with io.open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)

    c = payload["meta"]["counts"]
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  tracks={c['tracks']} papers={c['papers']} repos={c['repos']} "
          f"courses={c['courses']} milestones={c['milestones']}")
    total_tasks = sum(len(m["tasks"]) for t in payload["tracks"] for m in t["modules"])
    total_hours = sum(k["estimateHours"] for t in payload["tracks"]
                      for m in t["modules"] for k in m["tasks"])
    print(f"  tasks={total_tasks} estimated hours={total_hours}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
