#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
retime_schedule.py — 把每日执行时间从 14:00 改为 13:00（Asia/Shanghai）

为什么要用脚本而不是手动改：
  “14:00” 这个时间散落在 12+ 个文件里（采集器常量、分类元数据、manifest、
  前端提示文案、文档、PowerShell 入口、注册表调研产物、任务计划程序）。
  漏改任何一处都会造成前后矛盾 —— 例如界面写 14:00 而任务实际 13:00 跑，
  或者 config 里 cron 是 0 14 而 manifest.schedule 是 0 13。这个脚本一次性改完，
  并把改动清单打出来供核对。

用法:
  python scripts/retime_schedule.py --check     # 只报告还有哪些地方是 14:00
  python scripts/retime_schedule.py --apply     # 执行替换
"""
from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

OLD_H, NEW_H = 14, 13
OLD_TASK = "Future-Workbench-Daily-14"
NEW_TASK = "Future-Workbench-Daily-13"

# Every file that can mention the schedule. Data files (web/data/*) are
# regenerated by the collector, but taxonomy.json and manifest.json are only
# rewritten on a run, so they are patched here too or the UI keeps saying 14:00.
TARGETS = [
    "scripts/collect.py",
    "scripts/run-daily.ps1",
    "scripts/daily-agent.md",
    "scripts/selfcheck.py",
    "scripts/build_learning_kb.py",
    "scripts/build_site.py",
    "scripts/merge_registry.py",
    "scripts/plan_deep_read.py",
    "web/assets/js/views2.part.js",
    "web/assets/js/views.part.js",
    "web/assets/js/core.part.js",
    "web/assets/js/app.js",
    "web/index.html",
    "web/data/taxonomy.json",
    "web/data/manifest.json",
    "web/data/sources.json",
    "config/collector.config.json",
    "README.md",
    "FUTURE.md",
    "docs/信息架构与数据契约.md",
    "docs/登录类渠道操作手册.md",
    "research/source_registry.json",
]

# Ordered replacements. Longest/most specific first so we do not double-apply.
REPLACEMENTS: list[tuple[str, str]] = [
    (OLD_TASK, NEW_TASK),
    ('"cron": "0 14 * * *"', '"cron": "0 13 * * *"'),
    ("'0 14 * * *'", "'0 13 * * *'"),
    ('"0 14 * * *"', '"0 13 * * *"'),
    ("hour=14", "hour=13"),
    ("每日 14:00", "每日 13:00"),
    ("每天 14:00", "每天 13:00"),
    ("每日 14 点", "每日 13 点"),
    ("14:00（Asia/Shanghai）", "13:00（Asia/Shanghai）"),
    ("14:00 (Asia/Shanghai)", "13:00 (Asia/Shanghai)"),
    ("14:00 自动", "13:00 自动"),
    ("14:00 触发", "13:00 触发"),
    ("14:00 执行", "13:00 执行"),
    ("14:00 自动执行", "13:00 自动执行"),
    ("14:00（上海时间）", "13:00（上海时间）"),
    ("上海时间 14:00", "上海时间 13:00"),
    ("每天上海时间 **14:00**", "每天上海时间 **13:00**"),
    ("每日上海时间14:00", "每日上海时间13:00"),
    ("每日上海时间 14:00", "每日上海时间 13:00"),
    ("上海时间 14:00", "上海时间 13:00"),
    ("每天 14:00", "每天 13:00"),
    ("每日 14:00", "每日 13:00"),
    ("-At '14:00'", "-At '13:00'"),
    ("2026-10-01T14:00:00+08:00", "2026-10-01T13:00:00+08:00"),
    ("StartBoundary>14", "StartBoundary>13"),
    ("| 计划时间 | 每日 14:00 |", "| 计划时间 | 每日 13:00 |"),
    ("每日 14:00 (Asia/Shanghai)", "每日 13:00 (Asia/Shanghai)"),
    ("每日 14:00（Asia/Shanghai）", "每日 13:00（Asia/Shanghai）"),
    ("14:00 自动执行", "13:00 自动执行"),
    ("每天 14:00 自动执行的联网调研定时任务", "每天 13:00 自动执行的联网调研定时任务"),
]

# Catch-all: any remaining bare "14:00" surrounded by schedule-ish context.
BROAD_PATTERNS = [
    (r"14:00", "13:00"),
    (r"0 14 \* \* \*", "0 13 * * *"),
    (r"TaskName.*Daily-14", "TaskName Daily-13"),
    (r"Daily-14", "Daily-13"),
]


def patch_text(text: str) -> tuple[str, int]:
    n = 0
    for a, b in REPLACEMENTS:
        if a in text and a != b:
            c = text.count(a)
            text = text.replace(a, b)
            n += c
    return text, n


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="retime_schedule.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true", help="write the changes")
    ap.add_argument("--check", action="store_true", help="only report remaining 14:00 mentions")
    args = ap.parse_args(argv)

    if args.check or not args.apply:
        print("")
        print("仍有 14:00 / Daily-14 字样的位置：")
        total = 0
        for rel in TARGETS:
            p = ROOT / rel
            if not p.exists():
                continue
            try:
                text = p.read_text("utf-8")
            except Exception:
                continue
            hits = [i + 1 for i, line in enumerate(text.split("\n"))
                    if re.search(r"14:00|0 14 \* \* \*|Daily-14|hour=14", line)]
            if hits:
                total += len(hits)
                print(f"  {rel}: {len(hits)} 行  {hits[:8]}")
        print(f"\n合计 {total} 行。执行 `--apply` 全部改为 13:00。")
        return 0

    changed = []
    grand = 0
    for rel in TARGETS:
        p = ROOT / rel
        if not p.exists():
            print(f"  [skip] {rel} (not found)")
            continue
        try:
            text = p.read_text("utf-8")
        except Exception as e:
            print(f"  [skip] {rel} ({e})")
            continue
        new, n = patch_text(text)
        # Broad pass for anything the specific rules missed.
        for pat, rep in BROAD_PATTERNS:
            new2, k = re.subn(pat, rep, new)
            if k:
                new = new2
                n += k
        if n:
            with io.open(p, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(new)
            changed.append((rel, n))
            grand += n

    print("")
    print("=" * 66)
    print(f"已修改 {len(changed)} 个文件，共 {grand} 处：")
    for rel, n in changed:
        print(f"  {n:>4}  {rel}")
    print("=" * 66)

    # Verify nothing schedule-related still says 14.
    leftovers = []
    for rel in TARGETS:
        p = ROOT / rel
        if not p.exists():
            continue
        try:
            text = p.read_text("utf-8")
        except Exception:
            continue
        for i, line in enumerate(text.split("\n"), 1):
            if re.search(r"14:00|0 14 \* \* \*|Daily-14|hour=14", line):
                leftovers.append((rel, i, line.strip()[:110]))
    if leftovers:
        print("\n[!] 仍有残留（需人工确认是否属于别的时间含义）：")
        for rel, i, line in leftovers[:20]:
            print(f"  {rel}:{i}: {line}")
    else:
        print("\n[ok] 所有排期相关位置已统一为 13:00")
    print("")
    return 0


if __name__ == "__main__":
    sys.exit(main())
